// Generated by CoffeeScript 1.6.3
/*
#   Module dependencies.
*/

var program, stream, sync, updated;

program = require("commander");

program.version("0.0.1").option("-s, --stream [value]", "select Streamname(e.g.'nikezono')").parse(process.argv);

updated = 0;

stream = program.stream;

console.info("Add Stream '" + stream + "'. Please Wait for Sync");

process.nextTick(function() {
  sync(stream, updated);
  return setInterval(function() {
    return sync(stream, updated);
  }, 1000 * 60);
});

sync = function(stream, updated) {
  console.log(stream);
  return console.log(updated);
};
