// Generated by CoffeeScript 1.6.3
/*
#   Module dependencies.
*/

var async, cnumber, color, colors, moment, program, render, stream, updated, _;

program = require("commander");

_ = require('underscore');

async = require('async');

moment = require('moment');

colors = require('colors');

colors.setTheme({
  time: 'grey',
  verbose: 'cyan',
  prompt: 'grey',
  info: 'blue'
});

color = ["white", 'yellow', 'cyan', 'magenta', 'red', 'green', 'blue'];

cnumber = 0;

program.version("0.0.1").option("-s, --stream [value]", "select Streamname(e.g.'nikezono')").parse(process.argv);

updated = (new Date()).getTime() - 1000 * 60 * 60;

stream = program.stream;

process.nextTick(function() {
  /* socket.io Configration*/

  var client, socket;
  client = require('socket.io-client');
  socket = client.connect("http://unific.net");
  return socket.on('connect', function() {
    console.log("Add Stream '" + stream.blue + "'. Please Wait for Sync");
    socket.emit('sync stream', {
      stream: stream,
      latest: updated
    });
    socket.on('sync completed', function(pages) {
      var sorted;
      if (pages.length > 0) {
        sorted = _.sortBy(pages, function(obj) {
          return Date.parse(obj.page.pubDate);
        });
        updated = Date.parse(_.last(sorted).page.pubDate);
        return render(sorted);
      }
    });
    return setInterval(function() {
      return socket.emit('sync stream', {
        stream: stream,
        latest: updated
      });
    }, 1000 * 60);
  });
});

render = function(sorted) {
  return async.eachSeries(sorted, function(article, cb) {
    var date, seed, site, title;
    seed = parseInt(article.feed._id) + article.feed.title.length;
    cnumber = seed % color.length;
    date = ("[" + (moment(article.page.pubDate).format("hh:mm")) + "]").time;
    title = article.page.title[color[cnumber]];
    site = article.feed.site.underline;
    return setTimeout(function() {
      console.log("" + date + " " + title + " - " + site);
      return cb();
    }, 100);
  }, function() {});
};
